; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico_blink]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
build_src_filter = +<blink.cpp>

[env:pico_encoder]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
build_src_filter = +<encoder.cpp>

[env:pico_stepper]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
build_src_filter = +<stepper.cpp>

[env:pico_stepper_and_encoder]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
build_src_filter = +<stepper_and_encoder.cpp>


[env:pico_one_shot]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
build_src_filter = +<one_shot_encoder.cpp>

[env:pico_peripheral_test]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
build_src_filter = +<peripheral_test.cpp>


; src_filter = +<fourth.cpp>  ; Uncomment and replace with fourth source file when ready
